version: '3'
services:
  bot:
    build:
      context: ./
      dockerfile: bot.docker
    container_name: bot
    environment:
      - CONTAINER=bot
    volumes:
       - ./:/bot
    networks:
      - default